import os

DATABASE_URL: str = os.environ["DATABASE_URL"]
ASSEMBLYAI_PROXY_URL: str = os.environ["ASSEMBLYAI_PROXY_URL"]
ALOTECH_POLL_INTERVAL: int = int(os.getenv("ALOTECH_POLL_INTERVAL", "60"))
CREDENTIALS_ENCRYPTION_KEY: str = os.environ["CREDENTIALS_ENCRYPTION_KEY"]
